{% set version = "0.7-11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rsclient
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RSclient_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RSclient/RSclient_{{ version }}.tar.gz
  sha256: f9431e433e564820162cb8aef78306c6284db2ddc30ddbe91cb2dccb1a685c97

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
    - {{ posix }}gzip            # [win]
    - {{ posix }}tar             # [win]
  host:
    - r-base
    - openssl
    - zlib                       # [win]
  run:
    - r-base

test:
  commands:
    - $R -e "library('RSclient')"           # [not win]
    - "\"%R%\" -e \"library('RSclient')\""  # [win]

about:
  home: http://www.rforge.net/RSclient/
  license: GPL-2.0-only
  summary: Client for Rserve, allowing to connect to Rserve instances and issue commands.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - comatrion
